name: Commit Message Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  commit-message-lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Install Commitlint (Without using package.json)
      - name: Install Commitlint
        run: npm install @commitlint/cli @commitlint/config-conventional

      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4     

      # Step 3: Lint Commit Messages
      - name: Lint Commit Messages
        run: |
          npx commitlint --from=${{ github.event.before }} --to=${{ github.sha }}