name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    env:
      DOC_USER: ${{ secrets.DOC_USER }}
      DOC_PASS: ${{ secrets.DOC_PASS }}
      NODE_ENV: ${{ secrets.NODE_ENV }}

    runs-on: ubuntu-latest  

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Set environment variable from secret
    - name: Set Environment Variables
      run: echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test